feat：add products component
antvis/dumi-theme-antv pull request #17
Opened 2022-10-18 13:02 UTC by BoyYangzai

feat：add products component

2022-10-18 13:21 UTC, hustcc requested changes

2022-10-18 13:21 UTC, hustcc commented on .dumi/theme/slots/Header/Products/getProducts.tsx
> +  return products;
看看和后面的远程地址区别是什么，建议删除

2022-10-18 13:21 UTC, hustcc commented on .dumi/theme/slots/Header/Products/index.tsx
> +import classNames from 'classnames';
cx

2022-10-18 13:21 UTC, hustcc commented on .dumi/theme/slots/Header/index.tsx
> +  return <HeaderComponent {...Object.assign({}, headerProps, props)} />;
格式化

2022-10-18 13:21 UTC, hustcc commented on .dumi/theme/slots/utils.ts
> +  return s.charAt(0).toUpperCase() + s.slice(1);
_.capitalize

2022-10-18 13:21 UTC, hustcc commented on .dumi/theme/slots/utils.ts
> +  // antv.vision => antv.gitee.io
nit: antv.gitee.io 后续不用，改用 antv.antgroup.com

2022-10-18 13:21 UTC, hustcc commented on package.json
> +    "lodash": "^4.17.21",
已经有 lodash-es，@types/lodash

2022-10-18 18:17 UTC, BoyYangzai commented on .dumi/theme/slots/Header/Products/getProducts.tsx
> +  return products;
getProducts返回值是写好的死数据，getNewProducts是拿到的远程数据，前者函数在原来官网中暂时未调用，猜测：1.可能是为了应对服务器接口突发事故 2.原作者写的时候用这个函数拿死数据来测试，忘记删除
所以这里选择删掉getProducts函数

2022-10-19 01:16 UTC, hustcc approved these changes

2022-10-19 01:16 UTC, merged