fix: win路径解析错误
antvis/dumi-theme-antv pull request #208
Opened 2023-03-20 12:37 UTC by Anberm

2023-03-24 01:29 UTC, hustcc requested changes

2023-03-24 01:29 UTC, hustcc commented on src/plugin/utils.ts
> +export function winPath(path: string) {
可以举个栗子，是哪类 path 的处理问题吗？

2023-04-12 10:30 UTC, PeachScript commented on src/plugin/utils.ts
> +      return winPath(require.resolve(fullpath));
winPath 可以从 `dumi/plugin-utils` 里取

2023-04-12 12:00 UTC, Anberm commented on src/plugin/utils.ts
> +export function winPath(path: string) {
在window系统下的路径转换问题，这个在dumi/plugin-utils有处理的，但当前项目没处理

2023-04-12 12:01 UTC, Anberm commented on src/plugin/utils.ts
> +      return winPath(require.resolve(fullpath));
是的，但是当前项目没有依赖dumi/plugin-utils

2023-04-17 00:21 UTC, closed without merging