fix: change prettier to deps
antvis/dumi-theme-antv pull request #229
Opened 2023-05-19 22:47 UTC by NewByVector

`prettier` 在 `dependencies` 中有用到，改成 `dependencies`，不然上面应用会报错。

2023-05-22 01:52 UTC, hustcc requested changes

2023-05-22 01:52 UTC, hustcc commented on package.json
> +    "prettier": "^2.7.1"
这个应该放在 devDependencies 里面。

2023-06-06 12:04 UTC, NewByVector commented on package.json
> +    "prettier": "^2.7.1"
[import { format } from 'prettier';](https://github.com/antvis/dumi-theme-antv/blob/5f87018895a7677adceec63242107267da58fa9c/src/slots/CodeEditor/index.tsx#L6)   这里代码中有用到，放到 devDependencies 导致上基于这个的应用报错。

2023-06-06 12:19 UTC, hustcc approved these changes

2023-06-06 12:22 UTC, hustcc approved these changes

2023-06-06 12:22 UTC, merged