feat: api collapsed
antvis/dumi-theme-antv pull request #272
Opened 2024-01-03 12:40 UTC by lxfu1

1. 新增 API 折叠功能，增强可读性
2. API 解析支持 `<embed src="" />` 模式，兼容之前的API写法
3. `markdown-to-jsx` 替换为 `react-markdown`
4. API 预览宽度默认调整为 360

![image](https://github.com/antvis/dumi-theme-antv/assets/31396322/2148f38b-094f-4867-82f2-8ba6efe866c0)

2024-01-03 12:57 UTC, hustcc requested changes

2024-01-03 12:57 UTC, hustcc commented on package.json
> +  ]
有很多格式化的内容？

2024-01-03 13:02 UTC, lxfu1 commented on package.json
> +  ]
这个目测是之前提交的时候代码格式化没生效！

2024-01-03 13:23 UTC, hustcc commented on package.json
> +  ]
不格式化吧，格式化是按照key的字典顺序，不美观！

2024-01-04 13:35 UTC, hustcc approved these changes

2024-01-04 13:35 UTC, merged