fix: change the url for the product
antvis/dumi-theme-antv pull request #277
Opened 2024-02-02 08:47 UTC by sunsunmonkey

#276

2024-02-03 00:59 UTC, hustcc requested changes

2024-02-03 00:59 UTC, hustcc commented on src/slots/Detail/index.tsx
> +    fetch('https://assets.antv.antgroup.com/antv/products.json', // 生产环境
还是要用 banner那个文件。

2024-02-03 01:00 UTC, hustcc commented
另外，麻烦可以在 example 目录中运行一下，预览下站点是否正确。

2024-02-04 02:20 UTC, ai-qing-hai approved these changes
修改内部地址为线上

2024-02-04 02:25 UTC, hustcc approved these changes

2024-02-04 02:26 UTC, merged